=== ThierryAhn/my-master-1/semestre2/langage_web2/BDTheque/src/data/BD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.univ-rouen.fr/bd"
	xmlns:bd="http://www.univ-rouen.fr/bd" elementFormDefault="qualified">
	
	<!-- Type ISBN, source : http://regexlib.com-->
	<simpleType name="ISBN-type">
        <restriction base="string">
            <pattern value="(\s)*[0-9]+[- ][0-9]+[- ][0-9]+[- ][0-9]*[- ]*[xX0-9]"/>           
        </restriction>
    </simpleType>
	
	<element name="bds">
		<complexType>
			<sequence>
				<element maxOccurs="unbounded" name="bd">
					<complexType>
						<sequence>
							<!-- Infos BD -->
							<element name="Informations">
								<complexType>
									<sequence>
										<!-- Titre BD -->
										<element name="Titre" type="string" />

										<!-- Serie BD -->
										<element name="Serie" type="string" minOccurs="0"
											maxOccurs="1" />

										<!-- Identifiant de la BD -->
										<element name="Identifiant" type="int" />

										<!-- Scenario -->
										<element name="Scenario" type="string" />

										<!-- Dessin -->
										<element name="Dessin" type="string" />
										
										<!-- Couleurs -->
										<element name="Couleurs" type="string" />

										<!-- Editeur BD -->
										<element name="Editeur" type="string" />
										
										<!-- Format -->
										<element name="Format" type="string" />

										<!-- ISBN BD -->
										<element name="ISBN" type="bd:ISBN-type" />

										<!-- Date de creation BD -->
										<element name="Date" type="date" />
									</sequence>
								</complexType>
							</element>

							<!-- Images BD, que juste l'url -->
							<element name="Image" type="anyURI"/>
								
							<!-- Description BD -->
							<element name="Description">
								<complexType>
									<simpleContent>
										<extension base="string" />
									</simpleContent>
								</complexType>
							</element>

						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== ThierryAhn/my-master-1/semestre2/langage_web2/BDTheque/src/data/BD.xml
<?xml version="1.0" encoding="UTF-8"?>
<bds xmlns="http://www.univ-rouen.fr/bd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.univ-rouen.fr/bd BD.xsd ">
	<!-- À bout portant : Premier sang -->
	<bd>
		<!-- Informations -->
		<Informations>
			<Titre>Premier sang</Titre>
			<Serie>À bout portant</Serie>
			<Identifiant>1</Identifiant>
			<Scenario>Azzarello, Brian</Scenario>
			<Dessin> Risso, Eduardo </Dessin>
			<Couleurs>Goleash, Grant</Couleurs>
			<Editeur>Soleil Productions</Editeur>
			<Format>Grand format</Format>
			<ISBN>2-84565-138-4</ISBN>
			<Date>2002-01-19</Date>
		</Informations>

		<!-- Image -->
		<Image>http://www.bedetheque.com/media/Couvertures/aboutportantcouv01.jpg</Image>

		<!-- Description -->
		<Description> 
			Dizzy Cordova a tout perdu: son mari et son fils, tous deux victimes de la brutalité des gangs. A 
			peine sortie d'incarcération, la jeune femme est abordée par le mystérieux agent Graves. Ce dernier 
			lui offre la liste des vrais coupables, une arme, cent cartouches, mais surtout, lui garantit 
			l'immunité absolue. Dizzie empruntera-t-elle la voie de la rédemption, ou celle de la vengeance, au 
			risque de souiller son âme à jamais ?
		</Description>
	</bd>

	<bd>
		<!-- Informations -->
		<Informations>
			<Titre>Poupées Russes</Titre>
			<Serie>Lloyd Singer</Serie>
			<Identifiant>2</Identifiant>
			<Scenario>Brunschwig, Luc</Scenario>
			<Dessin>Neuray, Olivier</Dessin>
			<Couleurs>Cochet, Isabelle</Couleurs>
			<Editeur>Bamboo</Editeur>
			<Format>Grand format</Format>
			<ISBN>978-2-8189-0255-4</ISBN>
			<Date>2011-01-10</Date>
		</Informations>

		<!-- Image -->
		<Image>http://www.bedetheque.com/cache/thb_couv/Couv_121001.jpg</Image>

		<!-- Description -->
		<Description> 
			Elle s'appelle Zéna. En quittant sa Russie natale pour les États-Unis, elle croyait trouver amour et 
			opulence. Elle ne rencontra que l'enfer de la prostitution et de la pornographie. Après s'être enfuie
			pour protéger sa fille, Zéna est un témoin-clé pour le FBI. Mais Zéna a peur de tout, de tout le 
			monde, et ne veut pas parler… Il s'appelle Lloyd Singer. Son apparence malingre et insignifiante ne 
			reflète guère ses drames intimes. Orphelin à 13 ans, il a dû assumer seul la charge d'une famille, 
			sans jamais pouvoir s’offrir le luxe de l'égoïsme, et encaisser les coups des mauvais garçons de 
			Little Jerusalem. Aujourd'hui, il est comptable au FBI. Mais son véritable talent réside dans son 
			empathie. Lui seul saura établir un contact avec Zéna. Et si Lloyd Singer ne peut pas la protéger de 
			ses bourreaux, il reste Makabi, son alter ego. Makabi, le vengeur masqué, prêt à aller jusqu'au bout 
			pour protéger ceux qui souffrent… 
		</Description>
	</bd>
</bds>

=== ThierryAhn/my-master-1/semestre2/langage_web2/BDTheque/src/data/BD1.xml
<?xml version="1.0" encoding="UTF-8"?>
<bd xmlns="http://www.univ-rouen.fr/bd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.univ-rouen.fr/bd ../xsd/BD.xsd ">
	<!-- Informations -->
	<Informations>
		<Titre>Poupées Russes</Titre>
		<Serie>Lloyd Singer</Serie>
		<Identifiant>2</Identifiant>
		<Scenario>Brunschwig, Luc</Scenario>
		<Dessin>Neuray, Olivier</Dessin>
		<Couleurs>Cochet, Isabelle</Couleurs>
		<Editeur>Bamboo</Editeur>
		<Format>Grand format</Format>
		<ISBN>978-2-8189-0255-4</ISBN>
		<Date>2011-01-10</Date>
	</Informations>

	<!-- Image -->
	<Image>http://www.bedetheque.com/cache/thb_couv/Couv_121001.jpg</Image>

	<!-- Description -->
	<Description>
		Elle s'appelle Zéna. En quittant sa Russie natale pour les États-Unis,
		elle croyait trouver amour et
		opulence. Elle ne rencontra que l'enfer de la prostitution et de la
		pornographie. Après s'être enfuie
		pour protéger sa fille, Zéna est un témoin-clé pour le FBI. Mais Zéna a
		peur de tout, de tout le
		monde, et ne veut pas parler… Il s'appelle Lloyd Singer. Son apparence
		malingre et insignifiante ne
		reflète guère ses drames intimes. Orphelin à 13 ans, il a dû assumer seul la
		charge d'une famille,
		sans jamais pouvoir s’offrir le luxe de l'égoïsme, et encaisser les coups
		des mauvais garçons de
		Little Jerusalem. Aujourd'hui, il est comptable au FBI. Mais son véritable
		talent réside dans son
		empathie. Lui seul saura établir un contact avec Zéna. Et si Lloyd Singer ne
		peut pas la protéger de
		ses bourreaux, il reste Makabi, son alter ego. Makabi, le vengeur masqué,
		prêt à aller jusqu'au bout
		pour protéger ceux qui souffrent…
	</Description>
</bd>

=== ThierryAhn/my-master-1/semestre2/langage_web2/BDTheque/src/data/BDupload.xml
<?xml version="1.0" encoding="UTF-8"?>
<bds xmlns="http://www.univ-rouen.fr/bd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.univ-rouen.fr/bd BD.xsd ">
    <!-- À bout portant : Premier sang -->
    <bd>
        <!-- Informations -->
        <Informations>
            <Titre>Le jugement de Dieu</Titre>
            <Serie>Le Dernier Cathare</Serie>
            <Identifiant>499</Identifiant>
            <Scenario>Delalande, Arnaud</Scenario>
            <Dessin>Lambert, Éric</Dessin>
            <Couleurs>Pradelle, Bruno</Couleurs>
            <Editeur>12bis et Grasset</Editeur>
            <Format>Grand format</Format>
            <ISBN>978-2-356-48391-1</ISBN>
            <Date>2002-01-19</Date>
        </Informations>

        <!-- Image -->
        <Image>http://www.bedetheque.com/media/Couvertures/Couv_187448.jpg</Image>

        <!-- Description -->
        <Description> 
            "Trente ans. Près de trente ans se sont écoulés depuis qu'Escartille de Puivert, le troubadour devenu Parfait cathare, a perdu Louve dans la plaine de Muret.
             Enfin, il a retrouvé le prétendu trésor rapporté de Terre Sainte par son père, le Chevalier à la Rose.
        </Description>
    </bd>

    <bd>
        <!-- Informations -->
        <Informations>
            <Titre>Atlantis</Titre>
            <Serie>Prométhée</Serie>
            <Identifiant>387</Identifiant>
            <Scenario>Bec, Christophe</Scenario>
            <Dessin>Bec, Christophe</Dessin>
            <Couleurs>Gérard, Sébastien</Couleurs>
            <Editeur>Soleil Productions</Editeur>
            <Format>Grand format</Format>
            <ISBN>978-2-302-00442-9</ISBN>
            <Date>2008-02-12</Date>
        </Informations>

        <!-- Image -->
        <Image>http://www.bedetheque.com/media/Couvertures/promethee01_80910.jpg</Image>

        <!-- Description -->
        <Description> 
            Une série d'événements planétaires, totalement inexpliqués s'est déclenchée et s'abat 
            sur la planète jour après jour à 13 heure 13 minutes précises. Quelle en est l'origine ?
        </Description>
    </bd>
</bds>
