=== ThierryAhn/my-master-1/semestre2/langage_web2/CV/src/xsd/CV.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.univ-rouen.fr/cv" xmlns:cv="http://www.univ-rouen.fr/cv" elementFormDefault="qualified">
	<element name="cv">
		<complexType>
			<sequence>
				<!--  Titre du CV -->
				<element name="Titre" type="string" />
				
				<!--  Civilite -->
				<element name="Civilite">
					<complexType>
						<sequence>
							<element name="Nom" type="cv:nomSimpleType" />
							<element name="Prenom" type="string" />
							<element name="Age" type="cv:ageSimpleType"/>
							<!--  Adresse -->
							<element name="Adresse">
								<complexType>
									<sequence>
										<element name="NumeroRue" type="cv:rueSimpleType" />
										<element name="NomRue" type="string" />
										<element name="CodePostal" type="cv:codePostalSimpleType" />
										<element name="Ville" type="string" />
									</sequence>
								</complexType>
							</element>
							
							<element name="Telephone" type="cv:telephoneSimpleType" />
							<element name="Email" type="cv:emailSimpleType" />
							<element name="Image" type="string" />
						</sequence>
					</complexType>
				</element>
				<!--  Fin Civilite -->
				
				<!-- Formations -->
				<element name="Formations">
					<complexType>
						<sequence>
							<element maxOccurs="unbounded" name="Formation">
								<complexType>
									<sequence>
										<element name="Date" type="string" />
										<element name="Description" type="string" />
										<element name="Location" type="string" />
										<element name="Pays" type="string" />
									</sequence>
									<attribute name="id" type="int" />
									<attribute name="ecole" type="string" />
									<attribute name="titre" type="string" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<!--  Fin Formations -->
				
				<!-- Experiences -->
				<element name="Experiences">
					<complexType>
						<sequence>
							<element maxOccurs="unbounded" name="Experience">
								<complexType>
									<sequence>
										<element name="Date" type="string" />
										<element name="Description" type="string" />
										<element name="Location" type="string" />
										<element name="Pays" type="string" />
									</sequence>
									<attribute name="id" type="int" />
									<attribute name="titre" type="string" />
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<!--  Fin Experiences -->
			
				
				<!-- Competences -->
				<element maxOccurs="unbounded" name="Competences">

					<complexType>
						<sequence>
							<element maxOccurs="unbounded" name="Competence">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="titre" type="string" />
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
						<attribute name="titre" type="string" />
					</complexType>
				</element>
				<!--  Fin Competences -->
				
				<!--  Loisirs -->
				<element name="Loisirs">
					<complexType>
						<sequence>
							<element maxOccurs="unbounded" name="Loisir">
								<complexType>
									<simpleContent>
										<extension base="string">
											<attribute name="titre" type="string" />
										</extension>
									</simpleContent>
								</complexType>
							</element>
						</sequence>
					</complexType>
				</element>
				<!--  Fin Loisirs -->
			
			</sequence>
		</complexType>
	</element>
	
	<!--  restriction sur l'age : valeur positive et compris entre 16 et 75 -->
	<simpleType name="ageSimpleType">
		<restriction base="positiveInteger">
			<minInclusive value="16"/>
			<maxInclusive value="75"/>
		</restriction>
	</simpleType>
	
	<!--  restriction sur nom : que des lettres en majuscule -->
	<simpleType name="nomSimpleType">
    	<annotation>
     		<documentation>pattern value="[A-Z \-]*"</documentation>
 		</annotation>
      	<restriction base="token">
        	<pattern value="[A-Z \-]*"/>
      	</restriction>
 	</simpleType>
 	
 	<!--  restriction sur email, source : http://regexlib.com/DisplayPatterns.aspx?cattabindex=0&categoryId=1 -->
 	<simpleType name="emailSimpleType"> 
    	<restriction base="string"> 
      		<pattern value="(\w[-._\w]*\w@\w[-._\w]*\w\.\w{2,3})"/> 
    	</restriction> 
  	</simpleType> 
	
	<!--  restriction sur tel -->
	<simpleType name="telephoneSimpleType">
		<restriction base="string"> 
			<pattern value="[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}-[0-9]{2}"/>
		</restriction>
	</simpleType>
	
	<!--  restriction sur code postal -->
	<simpleType name="codePostalSimpleType">
		<restriction base="string"> 
			<pattern value="[0-9]{5}"/>
		</restriction>
	</simpleType>
	
	<!--  restriction sur numero de la rue -->
	<simpleType name="rueSimpleType">
		<restriction base="string"> 
			<pattern value="[0-9]+"/>
		</restriction>
	</simpleType>
</schema>

=== ThierryAhn/my-master-1/trunk/semestre2/langage_web2/CV/src/xml/CV.xml
<?xml version="1.0" encoding="UTF-8"?>
<cv xmlns="http://www.univ-rouen.fr/cv" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.univ-rouen.fr/cv xsd/cv.xsd ">
	 
	<Titre> Développeur Web</Titre>
	
	<Civilite>
		<Nom>AHOUNOU</Nom>
		<Prenom>Thierry</Prenom>
		<Age>23</Age>
		<Adresse>
			<NumeroRue>312</NumeroRue>
			<NomRue>Panorama Boulevard Siegfried</NomRue>
			<CodePostal>76000</CodePostal>
			<Ville>Mont Saint Aignan</Ville>
		</Adresse>
		<Telephone>06-18-61-05-03</Telephone>
		<Email>a_thierry@ymail.com</Email>
		<Image>image.jpg</Image>
	</Civilite>
	
	<Formations>
		<Formation id="1" ecole="Fac de sciences" titre="Master 1 Informatique">
			<Date>2012-2013</Date>
			<Description>Description Master 1 Informatique Rouen</Description>
			<Location>Rouen</Location>
			<Pays>France</Pays>
		</Formation>
		
		<Formation id="2" ecole="Fac de sciences" titre="Master 1 Informatique">
			<Date>2011-2012</Date>
			<Description>Description Master 1 Informatique</Description>
			<Location>Nantes</Location>
			<Pays>France</Pays>
		</Formation>
		
		<Formation id="3" ecole="Fac de sciences" titre="Licence 3 Informatique">
			<Date>2010-2011</Date>
			<Description>Description Licence 3 Informatique</Description>
			<Location>Le Havre</Location>
			<Pays>France</Pays>
		</Formation>
		
		<Formation id="4" ecole="IUT Le Havre" titre="DUT Informatique">
			<Date>2008-2010</Date>
			<Description>Description DUT Informatique</Description>
			<Location>Le Havre</Location>
			<Pays>France</Pays>
		</Formation>
		
		<Formation id="5" ecole="Porte de Normandie" titre="BAC Scientifique">
			<Date>2007-2008</Date>
			<Description>Description BAC Scientifique</Description>
			<Location>Verneuil/Avre</Location>
			<Pays>France</Pays>
		</Formation>
	</Formations>
	
	<Experiences>
		<Experience id="1" titre="Experience 1">
			<Date>2012-2013</Date>
			<Description>Description Experience 1</Description>
			<Location>Rouen</Location>
			<Pays>France</Pays>
		</Experience>
		
		<Experience id="2" titre="Experience 2">
			<Date>2011-2012</Date>
			<Description>Description Experience 2</Description>
			<Location>Nantes</Location>
			<Pays>France</Pays>
		</Experience>
	</Experiences>
	
	<Competences titre="Langage de Programmation">
		<Competence titre="Java"> 4 ans de formation en Java</Competence>
		<Competence titre="C++"> 2 ans de formation en C++</Competence>
	</Competences>
	
	<Competences titre="Logiciels de Bureautique">
		<Competence titre="Microsoft office "> Utilisation régulière</Competence>
		<Competence titre="OpenOffice"> Utilisation régulière</Competence>
	</Competences>
	
	<Loisirs>
		<Loisir titre="Football"> Pratique régulière, tous les week-ends</Loisir>
		<Loisir titre="Musculation"> SUAPS Rouen</Loisir>
		<Loisir titre="Boxe"> SUAPS Rouen</Loisir>
	</Loisirs>
	
</cv>
